FROM nginx:alpine

RUN echo "Joulica Reporting Dashboard Deployment"

COPY deploy/nginx.conf /etc/nginx/nginx.conf

# copy artifact build from the 'build environment'
COPY dist/app/ /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
