// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:fa16e91a-e43c-4a8c-b068-64941a1d7790",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_WFrZPCnYL",
    "aws_user_pools_web_client_id": "28o8g0nrk14458s554p1tbv5l7",
    "oauth": {}
};


export default awsmobile;
